#!/usr/bin/env bash
#
# deploy.sh — apply an overlay and wait for it to be serving.
#
# Usage:  scripts/deploy.sh [-o OVERLAY] [-s] [-n] [-h]
#
#   -o   overlay: dev | prod-shaped        (default: $OVERLAY, then dev)
#   -s   skip the install/upgrade Job
#   -n   dry run: render the manifests to stdout and apply nothing
#   -h   this header
#
# Environment overrides:
#   SITE           which store to serve   (default: vanilla.test)
#   OVERLAY        default overlay        (default: dev)
#   NAMESPACE      target namespace       (default: vanilla)
#   CLUSTER_NAME   kind cluster           (default: vanilla)
#   WAIT_TIMEOUT   per-rollout timeout    (default: 600s)
#   INSTALL_TIMEOUT  timeout for the install Job alone (default: 3600s)
#
# The install Job is deleted and recreated rather than applied, because a Job's
# pod template is immutable and a second `apply` over an existing one fails
# with a field-is-immutable error that reads like a manifest bug.
#
# It gets its OWN timeout, an order of magnitude longer than a rollout. A first
# install against an empty database builds the whole schema, runs every data
# patch and reindexes from nothing; timing that out at 600s and reporting a
# failed deploy would be wrong about work that was proceeding correctly.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "${HERE}/lib.sh"

SKIP_UPGRADE=0; DRY=0
while getopts ":o:snh" opt; do
    case "$opt" in
        o) OVERLAY="$OPTARG" ;;
        s) SKIP_UPGRADE=1 ;;
        n) DRY=1 ;;
        h) print_header "${BASH_SOURCE[0]}"; exit 0 ;;
        *) die "unknown flag -${OPTARG}; try -h" ;;
    esac
done

need kubectl
WAIT_TIMEOUT="${WAIT_TIMEOUT:-600s}"
INSTALL_TIMEOUT="${INSTALL_TIMEOUT:-3600s}"
DIR="${K8S_REPO_ROOT}/k8s/overlays/${OVERLAY}"
[[ -d "$DIR" ]] || die "no overlay at ${DIR}"

# --- which site the cluster is serving ---------------------------------------
# The cluster runs ONE store at a time and this is where it is told which. It
# binds 127.0.0.1:80 and cluster-up.sh refuses to exist beside a Compose stack,
# so there is no second port for a second hostname — multi-site is a Compose
# feature and saying otherwise here would be a claim the runtime cannot keep.
#
# For any site other than the base's own, a small overlay is GENERATED on top
# of the chosen one. Generated rather than committed because it is machine
# state: it names whichever store this cluster happens to be serving today,
# and a committed copy would be one more thing to disagree with reality.
#
# It carries exactly three things kustomize cannot interpolate: the site's env
# file merged into the ConfigMap, and the ingress host and TLS secret. The env
# file is COPIED in rather than referenced, because kustomize refuses to read a
# file outside the kustomization root -- the same restriction that keeps
# common.env under k8s/base.
[[ -f "$SITE_ENV_FILE" ]] || die "no site '${SITE}'. Existing sites: $(site_list | tr '\n' ' ')"
if [[ "$SITE_SLUG" != "vanilla-test" ]]; then
    # A dry run leaves nothing behind, so it renders from a temporary directory
    # that is removed on exit. It has to be a SIBLING of the overlay it builds
    # on: kustomize rejects an absolute path in `resources:` outright --
    #
    #   new root '/.../k8s/overlays/dev' cannot be absolute
    #
    # -- so `../dev` is the only reference that works, and that only resolves
    # from inside k8s/overlays.
    if [[ $DRY -eq 1 ]]; then
        GEN="$(mktemp -d "${K8S_REPO_ROOT}/k8s/overlays/.site-XXXXXX")"
        trap 'rm -rf "$GEN"' EXIT
    else
        GEN="${K8S_REPO_ROOT}/k8s/overlays/site"
        rm -rf "$GEN"; mkdir -p "$GEN"
    fi
    cp "$SITE_ENV_FILE" "${GEN}/site.env"
    cat > "${GEN}/kustomization.yaml" <<KUSTOMIZE
# GENERATED by scripts/deploy.sh for ${SITE}. Do not edit — every value here
# comes from k8s/base/config/env/sites/${SITE_SLUG}.env, and the next deploy
# overwrites this directory.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../${OVERLAY}

configMapGenerator:
  - name: vanilla-env
    behavior: merge
    envs:
      - site.env

patches:
  - target:
      kind: Ingress
      name: vanilla
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: ${SITE_HOST}
      - op: replace
        path: /spec/tls/0/hosts/0
        value: ${SITE_HOST}
      - op: replace
        path: /spec/tls/0/secretName
        value: ${SITE_SLUG}-tls
KUSTOMIZE
    DIR="$GEN"
    log "Serving ${SITE} — generated ${GEN} over overlay '${OVERLAY}'"
fi

if [[ $DRY -eq 1 ]]; then
    kubectl kustomize "$DIR"
    exit 0
fi

cluster_exists || die "no cluster '${CLUSTER_NAME}'. Run: make up"

# The consumer list and the consumer Deployments have to agree, and nothing in
# Kubernetes checks it. Checked before applying rather than after, because the
# failure is silent once it is running.
"${HERE}/verify-consumers.sh" -o "$OVERLAY"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

log "Rendering overlay '${OVERLAY}'"
kubectl kustomize "$DIR" > "${tmp}/all.yaml"

# The setup:upgrade Job is separated out and applied AFTER the data tier is
# ready. Two reasons, both learned the expensive way:
#
#   - backoffLimit is 0, so a Job that starts before MariaDB accepts
#     connections fails once and stays failed. Applying it with everything
#     else would make every first deploy look broken.
#   - a Job's pod template is immutable, so a second `apply` over an existing
#     one fails with a field-is-immutable error that reads like a manifest
#     bug rather than a lifecycle one. It is deleted and recreated instead.
#
# This is what a Helm chart would express as a pre-install hook. Kustomize has
# no hooks, and the honest way to say so is a script step rather than a
# pretence that ordering is not needed (ADR-002).
split_manifests() {
    python3 - "$1" "$2" "$3" <<'PYEOF'
import sys
src, want, dest = sys.argv[1], sys.argv[2] == "job", sys.argv[3]
docs = open(src).read().split("\n---\n")
def is_job(d):
    return "kind: Job" in d and "name: magento-install" in d
kept = [d for d in docs if is_job(d) == want and d.strip()]
open(dest, "w").write("\n---\n".join(kept) + "\n")
PYEOF
}

split_manifests "${tmp}/all.yaml" job    "${tmp}/job.yaml"
split_manifests "${tmp}/all.yaml" notjob "${tmp}/rest.yaml"

log "Applying workloads"
kc apply -f "${tmp}/rest.yaml"

log "Waiting for the data tier"
for s in mariadb opensearch rabbitmq valkey-session; do
    kc -n "$NAMESPACE" rollout status "statefulset/${s}" --timeout="$WAIT_TIMEOUT"
done
kc -n "$NAMESPACE" rollout status deployment/valkey-cache --timeout="$WAIT_TIMEOUT"

if [[ $SKIP_UPGRADE -eq 0 ]]; then
    log "Installing or upgrading the store (whichever the database needs)"
    kc -n "$NAMESPACE" delete job magento-install --ignore-not-found --wait=true
    kc apply -f "${tmp}/job.yaml"
    if ! kc -n "$NAMESPACE" wait --for=condition=complete job/magento-install --timeout="$INSTALL_TIMEOUT"; then
        warn "the install Job did not complete. Its output:"
        kc -n "$NAMESPACE" logs job/magento-install --tail=200 || true
        die "aborting before the application tier finishes rolling — a half-upgraded schema behind serving pods is worse than a failed deploy"
    fi
else
    log "Skipping the install/upgrade Job (-s)"
fi

log "Waiting for the application tier"
for d in php-fpm php-admin php-cron web web-admin web-cron varnish; do
    kc -n "$NAMESPACE" rollout status "deployment/${d}" --timeout="$WAIT_TIMEOUT"
done

log "Waiting for the consumers"
for d in $(kc -n "$NAMESPACE" get deploy -l vanilla.dev/tier=consumer -o name); do
    kc -n "$NAMESPACE" rollout status "$d" --timeout="$WAIT_TIMEOUT"
done

log "Deployed. Try: make smoke"
